//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.QualityControl
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должность.
    /// </summary>
    // *** Start programmer edit section *** (Должность CustomAttributes)

    // *** End programmer edit section *** (Должность CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДолжностьE", new string[] {
            "Код as \'Код\'",
            "Название as \'Название\'"})]
    [View("ДолжностьL", new string[] {
            "Код as \'Код\'",
            "Название as \'Название\'"})]
    public class Должность : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fНазвание;
        
        // *** Start programmer edit section *** (Должность CustomMembers)

        // *** End programmer edit section *** (Должность CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Должность.Код CustomAttributes)

        // *** End programmer edit section *** (Должность.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Должность.Код Get start)

                // *** End programmer edit section *** (Должность.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Должность.Код Get end)

                // *** End programmer edit section *** (Должность.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должность.Код Set start)

                // *** End programmer edit section *** (Должность.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Должность.Код Set end)

                // *** End programmer edit section *** (Должность.Код Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Должность.Название CustomAttributes)

        // *** End programmer edit section *** (Должность.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Должность.Название Get start)

                // *** End programmer edit section *** (Должность.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Должность.Название Get end)

                // *** End programmer edit section *** (Должность.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должность.Название Set start)

                // *** End programmer edit section *** (Должность.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Должность.Название Set end)

                // *** End programmer edit section *** (Должность.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДолжностьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностьE", typeof(IIS.QualityControl.Должность));
                }
            }
            
            /// <summary>
            /// "ДолжностьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностьL", typeof(IIS.QualityControl.Должность));
                }
            }
        }
    }
}
