//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.QualityControl
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Качество.
    /// </summary>
    // *** Start programmer edit section *** (Качество CustomAttributes)

    // *** End programmer edit section *** (Качество CustomAttributes)
    public enum Качество
    {
        
        // *** Start programmer edit section *** (Качество.Годен CustomAttributes)

        // *** End programmer edit section *** (Качество.Годен CustomAttributes)
        [Caption("Годен")]
        Годен,
        
        // *** Start programmer edit section *** (Качество.Брак CustomAttributes)

        // *** End programmer edit section *** (Качество.Брак CustomAttributes)
        [Caption("Брак")]
        Брак,
    }
}
