//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.QualityControl
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Продукция.
    /// </summary>
    // *** Start programmer edit section *** (Продукция CustomAttributes)

    // *** End programmer edit section *** (Продукция CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПродукцияE", new string[] {
            "Код as \'Код\'",
            "Название as \'Название\'"})]
    [View("ПродукцияL", new string[] {
            "Код as \'Код\'",
            "Название as \'Название\'"})]
    public class Продукция : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fНазвание;
        
        // *** Start programmer edit section *** (Продукция CustomMembers)

        // *** End programmer edit section *** (Продукция CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Продукция.Код CustomAttributes)

        // *** End programmer edit section *** (Продукция.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Продукция.Код Get start)

                // *** End programmer edit section *** (Продукция.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Продукция.Код Get end)

                // *** End programmer edit section *** (Продукция.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Продукция.Код Set start)

                // *** End programmer edit section *** (Продукция.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Продукция.Код Set end)

                // *** End programmer edit section *** (Продукция.Код Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Продукция.Название CustomAttributes)

        // *** End programmer edit section *** (Продукция.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Продукция.Название Get start)

                // *** End programmer edit section *** (Продукция.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Продукция.Название Get end)

                // *** End programmer edit section *** (Продукция.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Продукция.Название Set start)

                // *** End programmer edit section *** (Продукция.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Продукция.Название Set end)

                // *** End programmer edit section *** (Продукция.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПродукцияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПродукцияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПродукцияE", typeof(IIS.QualityControl.Продукция));
                }
            }
            
            /// <summary>
            /// "ПродукцияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПродукцияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПродукцияL", typeof(IIS.QualityControl.Продукция));
                }
            }
        }
    }
}
