//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.QualityControl
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Проверяемые.
    /// </summary>
    // *** Start programmer edit section *** (Проверяемые CustomAttributes)

    // *** End programmer edit section *** (Проверяемые CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПроверяемыеE", new string[] {
            "Количество as \'Количество\'",
            "Качество as \'Качество\'",
            "Продукция as \'Продукция\'",
            "Продукция.Название as \'Название\'"}, Hidden=new string[] {
            "Продукция.Название"})]
    [MasterViewDefineAttribute("ПроверяемыеE", "Продукция", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    public class Проверяемые : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.QualityControl.Качество fКачество;
        
        private IIS.QualityControl.Продукция fПродукция;
        
        private IIS.QualityControl.Отчет fОтчет;
        
        // *** Start programmer edit section *** (Проверяемые CustomMembers)

        // *** End programmer edit section *** (Проверяемые CustomMembers)

        
        /// <summary>
        /// Качество.
        /// </summary>
        // *** Start programmer edit section *** (Проверяемые.Качество CustomAttributes)

        // *** End programmer edit section *** (Проверяемые.Качество CustomAttributes)
        public virtual IIS.QualityControl.Качество Качество
        {
            get
            {
                // *** Start programmer edit section *** (Проверяемые.Качество Get start)

                // *** End programmer edit section *** (Проверяемые.Качество Get start)
                IIS.QualityControl.Качество result = this.fКачество;
                // *** Start programmer edit section *** (Проверяемые.Качество Get end)

                // *** End programmer edit section *** (Проверяемые.Качество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверяемые.Качество Set start)

                // *** End programmer edit section *** (Проверяемые.Качество Set start)
                this.fКачество = value;
                // *** Start programmer edit section *** (Проверяемые.Качество Set end)

                // *** End programmer edit section *** (Проверяемые.Качество Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Проверяемые.Количество CustomAttributes)

        // *** End programmer edit section *** (Проверяемые.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (Проверяемые.Количество Get start)

                // *** End programmer edit section *** (Проверяемые.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (Проверяемые.Количество Get end)

                // *** End programmer edit section *** (Проверяемые.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверяемые.Количество Set start)

                // *** End programmer edit section *** (Проверяемые.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Проверяемые.Количество Set end)

                // *** End programmer edit section *** (Проверяемые.Количество Set end)
            }
        }
        
        /// <summary>
        /// Проверяемые.
        /// </summary>
        // *** Start programmer edit section *** (Проверяемые.Продукция CustomAttributes)

        // *** End programmer edit section *** (Проверяемые.Продукция CustomAttributes)
        [PropertyStorage(new string[] {
                "Продукция"})]
        [NotNull()]
        public virtual IIS.QualityControl.Продукция Продукция
        {
            get
            {
                // *** Start programmer edit section *** (Проверяемые.Продукция Get start)

                // *** End programmer edit section *** (Проверяемые.Продукция Get start)
                IIS.QualityControl.Продукция result = this.fПродукция;
                // *** Start programmer edit section *** (Проверяемые.Продукция Get end)

                // *** End programmer edit section *** (Проверяемые.Продукция Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверяемые.Продукция Set start)

                // *** End programmer edit section *** (Проверяемые.Продукция Set start)
                this.fПродукция = value;
                // *** Start programmer edit section *** (Проверяемые.Продукция Set end)

                // *** End programmer edit section *** (Проверяемые.Продукция Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.QualityControl.Отчет.
        /// </summary>
        // *** Start programmer edit section *** (Проверяемые.Отчет CustomAttributes)

        // *** End programmer edit section *** (Проверяемые.Отчет CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Отчет"})]
        public virtual IIS.QualityControl.Отчет Отчет
        {
            get
            {
                // *** Start programmer edit section *** (Проверяемые.Отчет Get start)

                // *** End programmer edit section *** (Проверяемые.Отчет Get start)
                IIS.QualityControl.Отчет result = this.fОтчет;
                // *** Start programmer edit section *** (Проверяемые.Отчет Get end)

                // *** End programmer edit section *** (Проверяемые.Отчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проверяемые.Отчет Set start)

                // *** End programmer edit section *** (Проверяемые.Отчет Set start)
                this.fОтчет = value;
                // *** Start programmer edit section *** (Проверяемые.Отчет Set end)

                // *** End programmer edit section *** (Проверяемые.Отчет Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПроверяемыеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПроверяемыеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроверяемыеE", typeof(IIS.QualityControl.Проверяемые));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Проверяемые.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПроверяемые CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПроверяемые CustomAttributes)
    public class DetailArrayOfПроверяемые : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.QualityControl.DetailArrayOfПроверяемые members)

        // *** End programmer edit section *** (IIS.QualityControl.DetailArrayOfПроверяемые members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Проверяемые by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Проверяемые.
        /// </summary>
        public DetailArrayOfПроверяемые(IIS.QualityControl.Отчет fОтчет) : 
                base(typeof(Проверяемые), ((ICSSoft.STORMNET.DataObject)(fОтчет)))
        {
        }
        
        public IIS.QualityControl.Проверяемые this[int index]
        {
            get
            {
                return ((IIS.QualityControl.Проверяемые)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.QualityControl.Проверяемые dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
