//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.QualityControl
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип устройства.
    /// </summary>
    // *** Start programmer edit section *** (ТипУстройства CustomAttributes)

    // *** End programmer edit section *** (ТипУстройства CustomAttributes)
    public enum ТипУстройства
    {
        
        // *** Start programmer edit section *** (ТипУстройства.Поляризирующее CustomAttributes)

        // *** End programmer edit section *** (ТипУстройства.Поляризирующее CustomAttributes)
        [Caption("Поляризирующее")]
        Поляризирующее,
        
        // *** Start programmer edit section *** (ТипУстройства.Герметизирующее CustomAttributes)

        // *** End programmer edit section *** (ТипУстройства.Герметизирующее CustomAttributes)
        [Caption("Герметизирующее")]
        Герметизирующее,
    }
}
